package com.bloomlet.herobrine.structure;

import java.util.ArrayList;
import java.util.List;

import net.minecraft.core.component.DataComponents;
import net.minecraft.network.chat.Component;
import net.minecraft.server.network.Filterable;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.Items;
import net.minecraft.world.item.component.WrittenBookContent;

/**
 * THE STORY. TEN BOOKS, NUMBERED, ONE VOICE, IN ORDER.
 *
 * GENERATED. Do not edit this file — write tools/books/prose.py and run
 * tools/books/gen_books.py. Pagination is the reason: a page is about 114 pixels
 * wide and fourteen rows tall and overflow is SILENT, so a hand-edited paragraph
 * loses its last line and nobody finds out for months. Seven pages of the first
 * set were clipped exactly that way.
 *
 * WHO IS TELLING IT. Addexio. He lived in the first house, he was at every one
 * of these places while it happened, and he is the companion you can still find
 * who walks in out of the distance at that same first house — see
 * Company.arrives. Book 10 is addressed to you and its last page is the man
 * already standing next to you, which is the whole reason the books are
 * numbered rather than scattered.
 *
 * HE IS A HERO WHO FAILED. He had a weapon every time. Book 4 is the one the
 * rest hangs off: he was thirty feet from a church with four children in it,
 * holding an iron sword, and he stayed behind a cart. He writes it in one
 * sentence and does not soften it. The arc after that goes downward — a tower
 * watching the wrong direction, a prison his own town built, a fight he lost,
 * and a wall he helped put up over a door instead of going through it.
 *
 * WHAT REPLACED WHAT. There were twenty-two books in ten hands: Alma's house
 * book, Toby's, Joren's protocol, Kadmus on the watch, and Steve's six documents
 * laid over the top. Every one was good and the whole was unreadable — a player
 * finds these one at a time, hours apart, between two other things, and
 * assembling a plot out of ten strangers' diaries is a thing nobody does.
 *
 * Steve is still in it. He is a character in Addexio's account now instead of
 * its narrator, and book 7 is where he arrives: the man with the book who came
 * to the prison and was only ever testing himself.
 *
 * WHAT EVERY BOOK HAS TO DO, or it is scenery:
 *
 *   MAKE THIS PLACE MATTER   what happened in the room you are standing in
 *   POINT AT THE NEXT ONE    by name, with a reason to walk there
 *   MOVE THE STORY ON        so that the order is not decoration
 *
 * Book 1 is in the farmhouse chest WITH THE MAP, because page one says "There is
 * a map in this chest" — the two cannot be separated any more without making the
 * text wrong. Book 6 carries the mimic tells that used to be theProtocol, in the
 * building that was dug to answer that exact question and answered it the worst
 * possible way.
 *
 * EASY WORDS AND SHORT LINES. Nineteen characters to a line means a long word
 * costs a line and a subordinate clause costs a page, and it is read on a screen
 * by somebody who is being hunted.
 */
public final class HouseBooks {
	private HouseBooks() {}

	// SIX BOOKS, ONE IN EVERY PLACE, SIX PAGES OR FEWER. Each says what happened
	// where you are standing and where the next one is. They were ten, and two
	// or three to a house, and the ones that were not the story were noise.

	/** 1. the farm. */
	public static ItemStack one() {
		return book("1. the farm", "Addexio",
			"""
			1. THE FARM.

			My name is Addexio.
			This was my home.

			There are six of
			these books. One at
			every place it
			happened. Read them
			in order.""",

			"""
			The night it began my
			daughter Lise came in
			from the barn white
			as milk. A man was
			standing in the corn
			with no lantern. No
			face she could
			describe. Only the
			eyes.""",

			"""
			I went out with the
			axe. The corn was
			flat in a circle
			twenty paces wide,
			as if something had
			stood there a long
			time. One set of
			footprints. They did
			not lead in. They
			did not lead out.""",

			"""
			Three nights later
			the barn burned with
			the animals shut in.
			The bolt was thrown
			from the OUTSIDE.
			Lise said he watched
			from the roof.
			Smiling. She said he
			knew her name.""",

			"""
			Then Lise was gone.
			Her bed was warm. The
			door was still
			barred. On the
			window, from the
			inside, one word in
			something that was
			not ink:

			MINE.""",

			"""
			I drew the way to the
			town and put the map
			where he would not
			look: at the top of
			the tower.

			Do not sleep on the
			road. He does not.

			- A.""");
	}

	/** 2. the town. */
	public static ItemStack two() {
		return book("2. the town", "Addexio",
			"""
			2. THE TOWN.

			I came here for help.
			I got here two days
			after he did.""",

			"""
			The baker, Tomas,
			held his own girl
			under the trough
			until she stopped
			kicking. Then he
			dried his hands and
			asked the square who
			wanted bread. His
			eyes had a dot in
			them.""",

			"""
			They hanged Tomas at
			noon. At dusk he was
			back in the bakery
			with the rope still
			on. Baking.

			The smell was not
			bread.""",

			"""
			Half of them went
			underground to get
			away from the sky.
			They took the
			children with them.
			Under the church
			there is a stair.
			I have been down
			once. I will not go
			again.""",

			"""
			Some of them still
			answer if you call.
			They use the right
			names. Do not answer
			back. That is how he
			learns your voice.""",

			"""
			The way on is in the
			library under the
			church. Take it and
			leave. Nothing in
			this town is asking
			to be saved.

			- A.""");
	}

	/** 3. under the hill. */
	public static ItemStack three() {
		return book("3. under the hill", "Addexio",
			"""
			3. UNDER THE HILL.

			This is where he
			lived. Not haunted.
			LIVED. There is a
			bed. He slept in it.""",

			"""
			Look at the table.
			Set for two. He ate
			across from an empty
			chair every night
			for years, and
			somebody washed the
			second plate.""",

			"""
			In the far room the
			shelves are full. Not
			books. Names. Every
			soul from every farm
			for forty miles, in
			the same hand, and a
			line through most of
			them.""",

			"""
			Lise is on the third
			shelf.

			There is no line
			through her yet.

			I stood there until
			the candle went out.""",

			"""
			He came back while I
			was here. I heard him
			on the stair and hid
			in the pool. He stood
			over the water a long
			time. He knew. He let
			me live so I would
			write this down.""",

			"""
			The way to the
			prison is in the
			chest by the stair.
			He wanted me to have
			it.

			Go anyway.

			- A.""");
	}

	/** 4. cell nine. */
	public static ItemStack four() {
		return book("4. cell nine", "Addexio",
			"""
			4. CELL NINE.

			They built this to
			keep him out. They
			ended up keeping
			each other in.""",

			"""
			The rule was simple.
			If you were not
			yourself, you went in
			a cell. Anyone could
			say it of anyone. By
			the second month the
			warder was in four,
			and the man who put
			him there was in six.""",

			"""
			Marta from the mill
			scratched STILL
			MYSELF on her wall
			every morning for
			eleven days. On the
			twelfth the scratches
			were on the ceiling
			and the door was
			still locked.""",

			"""
			Cell nine. They put
			a boy in it on a
			Tuesday because he
			would not blink.
			Wednesday there was
			blood on the ceiling
			and nothing on the
			floor. Nothing.

			Not even the boy.""",

			"""
			Something is in nine
			now. It is very tall
			and it does not move
			while you look at
			it.

			Look at it. Keep
			looking. Walk
			backwards to the
			stair.""",

			"""
			The last of them dug
			out through the back
			wall and kept going.
			The tunnel is still
			there. So is the
			map. Take the map.

			Do not take the
			tunnel at night.

			- A.""");
	}

	/** 5. the church. */
	public static ItemStack five() {
		return book("5. the church", "Addexio",
			"""
			5. THE CHURCH.

			He lived under the
			altar. UNDER it. The
			priest fed him for a
			year and called it
			prayer.""",

			"""
			Eleven of us went
			down the altar stair
			to bring him up.
			Four came back. Not
			the same four that
			went down. The faces
			were right.

			The eyes were his.""",

			"""
			Father Ambrose
			walked into the fire
			he had lit for us and
			did not scream. He
			looked at me the
			whole time.

			That was not Ambrose
			behind the eyes.""",

			"""
			I killed one of the
			four that night. It
			had my brother's
			face. I do not know
			if it was my brother.

			I have not slept
			since. That is three
			years.""",

			"""
			What is left of the
			village is here. We
			are going to the last
			house. There is a way
			through. We have
			decided.

			Most of us will not
			come back. I know.""",

			"""
			If you are reading
			this, we failed. The
			map is in the chest.

			Do what we could
			not.

			- A.""");
	}

	/** 6. the last house. */
	public static ItemStack six() {
		return book("6. the last house", "Addexio",
			"""
			6. THE LAST HOUSE.

			Nineteen of us came
			down these stairs.
			Eleven came back up.

			I am writing this on
			the way down again.""",

			"""
			The door under the
			floor is not a door.
			It is a mouth. It
			breathes. Put your
			hand near it and
			your hand is colder
			for a day.""",

			"""
			Eight went through.
			We heard them for
			about a minute. Then
			we heard ONE voice
			speaking with all
			eight mouths, and it
			was saying our names.""",

			"""
			Jorunn came back.
			Only Jorunn. She
			stood in the frame
			and said IT IS
			BEAUTIFUL and her
			teeth were wrong.

			I put her down
			myself. God forgive
			me.""",

			"""
			On the other side is
			a city he built out
			of the people he
			took. Over it, a
			castle. He is in it.
			He is waiting.

			He has been waiting
			for YOU.""",

			"""
			The door does not
			open twice. Go
			through and you
			finish it, or you
			stay.

			I am going. Come and
			find me.

			- Addexio.""");
	}

	private static final int TITLE_FITS = 32;

	private static String title(String wanted) {
		if (wanted.length() <= TITLE_FITS) {
			return wanted;
		}
		int cut = wanted.lastIndexOf(' ', TITLE_FITS);
		String short_ = wanted.substring(0, cut > 12 ? cut : TITLE_FITS).trim();
		com.bloomlet.herobrine.HerobrineMod.LOGGER.warn(
			"book title was {} characters and the wire allows {} — \"{}\" became \"{}\"",
			wanted.length(), TITLE_FITS, wanted, short_);
		return short_;
	}

	private static ItemStack book(String title, String author, String... pages) {
		List<Filterable<Component>> written = new ArrayList<>();
		for (String page : pages) {
			written.add(Filterable.passThrough(Component.literal(page)));
		}
		ItemStack stack = new ItemStack(Items.WRITTEN_BOOK);
		stack.set(DataComponents.WRITTEN_BOOK_CONTENT, new WrittenBookContent(
			Filterable.passThrough(title(title)), author, 0, written, true));
		return stack;
	}
}
