package com.bloomlet.herobrine.structure;

import java.util.ArrayList;
import java.util.List;

import net.minecraft.core.component.DataComponents;
import net.minecraft.network.chat.Component;
import net.minecraft.server.network.Filterable;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.Items;
import net.minecraft.world.item.component.WrittenBookContent;

/**
 * THE STORY. TEN BOOKS, NUMBERED, ONE VOICE, IN ORDER.
 *
 * GENERATED. Do not edit this file — write tools/books/prose.py and run
 * tools/books/gen_books.py. Pagination is the reason: a page is about 114 pixels
 * wide and fourteen rows tall and overflow is SILENT, so a hand-edited paragraph
 * loses its last line and nobody finds out for months. Seven pages of the first
 * set were clipped exactly that way.
 *
 * WHO IS TELLING IT. Addexio. He lived in the first house, he was at every one
 * of these places while it happened, and he is the companion you can still find
 * who walks in out of the distance at that same first house — see
 * Company.arrives. Book 10 is addressed to you and its last page is the man
 * already standing next to you, which is the whole reason the books are
 * numbered rather than scattered.
 *
 * HE IS A HERO WHO FAILED. He had a weapon every time. Book 4 is the one the
 * rest hangs off: he was thirty feet from a church with four children in it,
 * holding an iron sword, and he stayed behind a cart. He writes it in one
 * sentence and does not soften it. The arc after that goes downward — a tower
 * watching the wrong direction, a prison his own town built, a fight he lost,
 * and a wall he helped put up over a door instead of going through it.
 *
 * WHAT REPLACED WHAT. There were twenty-two books in ten hands: Alma's house
 * book, Toby's, Joren's protocol, Kadmus on the watch, and Steve's six documents
 * laid over the top. Every one was good and the whole was unreadable — a player
 * finds these one at a time, hours apart, between two other things, and
 * assembling a plot out of ten strangers' diaries is a thing nobody does.
 *
 * Steve is still in it. He is a character in Addexio's account now instead of
 * its narrator, and book 7 is where he arrives: the man with the book who came
 * to the prison and was only ever testing himself.
 *
 * WHAT EVERY BOOK HAS TO DO, or it is scenery:
 *
 *   MAKE THIS PLACE MATTER   what happened in the room you are standing in
 *   POINT AT THE NEXT ONE    by name, with a reason to walk there
 *   MOVE THE STORY ON        so that the order is not decoration
 *
 * Book 1 is in the farmhouse chest WITH THE MAP, because page one says "There is
 * a map in this chest" — the two cannot be separated any more without making the
 * text wrong. Book 6 carries the mimic tells that used to be theProtocol, in the
 * building that was dug to answer that exact question and answered it the worst
 * possible way.
 *
 * EASY WORDS AND SHORT LINES. Nineteen characters to a line means a long word
 * costs a line and a subordinate clause costs a page, and it is read on a screen
 * by somebody who is being hunted.
 */
public final class HouseBooks {
	private HouseBooks() {}

	// ---- 1. THE FARM --------------------------------------------------

	/**
	 * 1. THE FARM. Who he is, who Herobrine is, and the first small wrong things —
	 * torches out in a line, a door open and still, prints going one way. Ends by
	 * sending you down the passage under the outbuilding, which is where book 2 is.
	 */
	public static ItemStack one() {
		return book("1. the farm", "Addexio",
			"""
			1. THE FARM.

			My name is Addexio. I
			lived here.

			I am leaving ten of
			these. One at every
			place it happened.
			Read them in order
			and you will know what
			I know.""",

			"""
			There is a map in this
			chest. I drew it. It
			shows the next place.

			I grew wheat in the
			north field for eleven
			years. I had a wife. We
			had no children, and I
			was glad of that later.

			WHO WAS HERE BEFORE
			ME.""",

			"""
			A man called Steve
			farmed this valley
			first. He had a friend.
			The two of them went
			under the hill behind
			my north field looking
			for iron, and they
			found a door down
			there.

			Steve did not touch it.

			His friend did.""",

			"""
			His friend is called
			Herobrine. Write the
			name down. Everyone
			here learned to say
			\"him\" instead, and
			saying \"him\" is how a
			thing grows.

			WHAT I SAW FIRST.""",

			"""
			Small things. My
			torches went out in a
			line, one after
			another, from the
			barn to the house.

			A door I had shut
			standing open. Not
			swinging. Open, and
			still.""",

			"""
			Boot prints in the wet
			field going one way
			only. Out, and never
			back.

			I told myself it was
			foxes. I told my wife it
			was foxes. She
			stopped asking after
			a while, and that was
			worse.

			WHERE TO GO.""",

			"""
			Under my outbuilding
			there is a passage. I
			dug it myself. The next
			book is in a crate at
			the end of it.

			Go down there first. It
			says why I dug it.""");
	}

	/**
	 * 2. WHAT I SAW. The thing standing in his wheat that does not breathe, and the
	 * only chapter where he does something right: he boards his neighbours' windows
	 * and carries Marek's children to the town. Then the rider arrives.
	 */
	public static ItemStack two() {
		return book("2. what I saw", "Addexio",
			"""
			2. WHAT I SAW.

			I dug this passage to
			hide my wife in.

			That is the truth and
			it took me a year to
			write it down.""",

			"""
			Eleven feet down and
			thirty long, at night, in
			the spring, so that
			nobody would ask. I
			told the neighbours it
			was for roots.

			WHAT MADE ME DIG.

			I was walking the
			fence line at dusk.""",

			"""
			There was a man
			standing in my wheat,
			forty paces off. Grey
			shirt. Arms down.
			Facing me.

			I raised my hand to
			him.""",

			"""
			He did not move. I
			counted to a hundred
			and he did not move,
			and he did not
			breathe, and the
			wheat did not move
			around him either.

			Then I looked at his
			face. There was
			nothing in it. Just
			white, where eyes go.""",

			"""
			I ran. I am not
			ashamed of the
			running.

			WHAT I DID NEXT.

			I went to my
			neighbours. Otto, and
			Marek, and old Bren
			who could not walk
			far.""",

			"""
			I helped them board
			their windows. I
			carried Marek's
			children to the town
			myself, two at a time,
			because he had four
			and one horse.

			And I told all of them
			it would pass.""",

			"""
			I was wrong. I have
			been wrong about
			nearly every single
			thing in these ten
			books. Read them
			anyway. Being wrong in
			order is still a map.

			WHERE TO GO.""",

			"""
			On the eleventh day a
			rider came down the
			valley road with blood
			on his coat and could
			not finish a sentence.

			Ashfold. The walled
			town, north of here. It
			had already started
			there.

			The map from the
			farmhouse points at it.
			Go.""");
	}

	// ---- 2. THE TOWN --------------------------------------------------

	/**
	 * 3. THE TOWN. Ashfold on the twelfth day — every dog facing one way, nine people
	 * wearing other people's faces, and the tall one walking down the main street
	 * with its mouth open. Bren shoots it twice and it keeps walking.
	 */
	public static ItemStack three() {
		return book("3. the town", "Addexio",
			"""
			3. THE TOWN.

			Ashfold had four
			hundred people and a
			wall, and the wall is
			why nobody was
			afraid.

			I got here on the
			twelfth day. Not the
			first day. The twelfth.
			I want that written
			down.""",

			"""
			WHAT WAS ALREADY
			WRONG.

			The animals. Every
			dog in the town was
			facing the same way
			and not one of them
			was barking.""",

			"""
			The bell in the church
			rang once, at nothing.
			I climbed up to see
			who had pulled it.
			There was nobody in
			the tower.

			And the people in the
			street were talking
			about ordinary things,
			and it took me an hour
			to work out why that
			felt so bad.""",

			"""
			They were all saying
			the same ordinary
			things.

			THE ONES WEARING
			FACES.

			A woman I knew called
			my name from a
			doorway.""",

			"""
			She had my name right
			and her mouth was
			wrong. It moved a
			moment after the
			sound came out.

			I said her husband's
			name back to her. She
			smiled and did not
			answer. She did not
			know it.""",

			"""
			There were nine of
			them in the town by
			then. Nine people who
			were not those people
			any more. You could
			stand a foot away and
			still not be sure.

			THE TALL ONE.""",

			"""
			Then something came
			down the main street
			that was not
			pretending to be
			anybody.

			Three of us watched
			it from the smithy
			roof. It had the shape
			of a villager and it
			was as tall as the
			doorframes, and its
			mouth was open, and it
			stayed open.""",

			"""
			It did not run. It
			walked. It did not stop
			walking, and
			everything in front of
			it moved aside or
			stopped being able to.

			Bren shot it twice. It
			turned its head,
			looked at him, and kept
			walking.

			WHERE TO GO.""",

			"""
			The next book is in
			this same chest.

			I wrote it four years
			later in a cellar and I
			could not finish it in
			one sitting. Read it
			anyway.

			You need to know what
			he actually came here
			for.""");
	}

	/**
	 * 4. WHAT HE DID HERE. The worst book in the mod and the one the rest hangs off.
	 *
	 * The door in the square, forty-one people walked through it, and then the
	 * church roof and Marek's four children. Addexio was thirty feet away with an
	 * iron sword and stayed behind the cart. He says so in one sentence and does
	 * not soften it, which is the whole character in one line.
	 */
	public static ItemStack four() {
		return book("4. what he did here", "Addexio",
			"""
			4. WHAT HE DID HERE.

			I have started this
			book nine times.

			WHAT HE CAME FOR.

			He did not come to kill
			the town. Killing the
			town was tidying up
			afterwards.""",

			"""
			He came for the ones
			who would fit through
			the door.

			THE DOOR.

			On the third night
			there was a door
			standing in the square
			with nothing around it.""",

			"""
			Not a doorway. A
			frame of black stone,
			and inside it a purple
			light that moved like
			water standing on its
			end.""",

			"""
			They walked people
			through it. The nine
			wearing faces took
			them by the arms, and
			the tall one came
			behind, and the people
			went, because the
			things holding them
			had their sisters'
			faces on.""",

			"""
			Forty-one people
			went through. I
			counted the ones who
			never came out and
			forty-one is the
			number.

			I do not know where it
			goes. The air that
			came out of it was
			cold and smelled like a
			struck match. Nobody
			has ever come back
			through it.""",

			"""
			WHAT HE DID TO THE
			REST.

			The rest he did
			himself, in the open, in
			the middle of the day,
			so that we would
			watch.

			He started with the
			ones who could not
			run.""",

			"""
			Marek's four children
			were in the church
			with the cleric and
			eleven women. He came
			in through the roof.
			He did not use a
			sword. There was
			almost no noise and it
			took him less than a
			minute.

			I was thirty feet away,
			behind a cart, with an
			iron sword in my hand.""",

			"""
			I did not move.

			That is the sentence. I
			have written nine
			versions of this book
			to get around it. I had
			a weapon, I was close
			enough, and I stayed
			behind the cart.

			When he came out he
			looked straight at me.
			He knew exactly where
			I was.""",

			"""
			He let me live. I have
			thought about why for
			sixty years. I think
			somebody had to tell
			it.

			AND THEN HE WAS GONE.""",

			"""
			Two hundred and six
			dead. Forty-one
			through the door. He
			walked out of the
			north gate at dawn
			and the valley did not
			see him again for nine
			years.

			Some of what we
			buried we could not
			tell apart, so we
			buried it together and
			put up one stone.""",

			"""
			WHERE TO GO.

			Nine years is a long
			time to feel safe and
			we used it badly.

			We built a tower north
			of here to watch for
			him. It is still standing.
			The next book is at
			the top of it.

			Watching was not the
			problem.""");
	}

	// ---- 3. THE TOWER -------------------------------------------------

	/**
	 * 5. THE TOWER. Nine years of watching the wrong direction. Pip comes up the
	 * ladder shaking, nobody believes him, four go down and two come back — and
	 * what is under the tower turns out to be ours, not his.
	 */
	public static ItemStack five() {
		return book("5. the tower", "Addexio",
			"""
			5. THE TOWER.

			We built this to watch
			the horizon.

			Three of us put it up
			in one summer. Otto, a
			lad called Pip who was
			seventeen, and me.
			Ninety feet of stone, a
			room at the top, and a
			bell.""",

			"""
			Somebody stood in it
			every night for nine
			years. I took the
			winter watches. I do
			not sleep well anyway.

			WHAT WAS WRONG WITH
			IT.

			Everything. It is a
			good tower and it is
			the most stupid thing I
			have ever helped
			build.""",

			"""
			We watched the
			horizon because we
			thought he would come
			from somewhere.

			He does not come
			from somewhere. He is
			already where you
			are, and the reason
			you cannot see him is
			not distance.

			WHAT PIP FOUND.""",

			"""
			In the ninth summer
			Pip went down to the
			spring below the
			tower to clear the
			pipe.

			He came back up the
			ladder shaking so
			hard he could not
			hold the rungs.""",

			"""
			He said there was a
			hole in the rock that
			had not been there
			yesterday, with steps
			going down it, cut
			square.

			He said there was a
			light at the bottom the
			colour of a bruise.

			He said he could hear
			somebody counting.""",

			"""
			We did not believe him.
			Write that down too.

			Four of us went down
			the next morning to
			prove there was
			nothing.

			Two of us came back
			up.

			WHERE TO GO.""",

			"""
			Here is the part
			nobody is ready for,
			and it is worse than
			the other way round.

			What was under this
			tower was not his.""",

			"""
			It was ours. Men from
			the town cut those
			steps, and they had
			been cutting them the
			whole nine years we
			spent up here looking
			at the sky.

			The map points at it. It
			is a prison. Fourteen
			cells, iron on every
			door, and a desk at
			the end with a ledger
			on it.""",

			"""
			Read the ledger. Then
			read the book beside
			it.""");
	}

	// ---- 4. THE GAOL --------------------------------------------------

	/**
	 * 6. THE PRISON. What the gaol was for, and Joren's ledger with two columns where
	 * the out column is shorter.
	 *
	 * Also the only place in the mod that tells you how to beat the mimic, and
	 * every tell is real: it closes the last paces itself, copies your crouch,
	 * ransacks containers without taking anything, changes its coat, and only ever
	 * does any of it while you are alone.
	 */
	public static ItemStack six() {
		return book("6. the prison", "Addexio",
			"""
			6. THE PRISON.

			Fourteen cells cut
			into rock. Iron on
			every door. A desk at
			the far end with a
			lamp.

			The men who dug this
			were not monsters.
			That goes at the top,
			because it is the only
			part that is actually
			frightening.""",

			"""
			WHAT IT WAS FOR.

			Some people came
			back.""",

			"""
			Not through the door
			in the square. From
			smaller things. A night
			lost in the woods. A
			shaft that went too
			deep. A face at a
			window. They would be
			gone a day or a week,
			and then they would
			walk home.

			And they would be
			almost right.""",

			"""
			They knew their own
			names. They knew
			their children. They
			would sit at their own
			table and eat with
			their own hands, and
			then one evening they
			would say a sentence
			that only a dead man
			could know.

			So the town built
			somewhere to put
			them.""",

			"""
			HOW IT WORKED.

			You brought them in
			and you counted them
			in. It is painted on the
			wall by the gate.
			COUNT THEM IN. COUNT
			THEM OUT.""",

			"""
			The warder was a fair
			man called Joren and
			he kept a careful
			ledger, and that
			ledger is the worst
			object in this valley.

			It has two columns. In,
			and out.

			The out column is
			shorter. The missing
			names are not marked
			dead.""",

			"""
			HOW TO TELL, AFTER
			ALL THAT.

			They did work it out in
			the end. Not from the
			cutting. From watching.
			Learn this properly,
			because you will need
			it and I will not be
			there.""",

			"""
			The eyes. A dot in the
			middle of each one,
			black, where a man has
			nothing. He does not
			blink it away.

			If you are close
			enough to see it you
			are already too close.""",

			"""
			He does not sleep.
			The doors shut, the
			lights go, and one of
			them is still on the
			square, facing your
			house.

			Count the beds against
			the men. Every village
			has one now.""",

			"""
			He stops when you look
			at him. Not like a man
			caught out. Like a
			clock with a hand laid
			on it. Turn your back
			and he is nearer.

			WHERE TO GO.

			There is a second
			book in this chest and
			it is not mine.""",

			"""
			It is what one man said
			out loud, in a room
			with me and two
			others, over about
			four hours, after we
			got him out of cell
			nine.

			I wrote it down as he
			said it. I did not tidy it.""",

			"""
			If you would rather
			not, close the chest.
			It does not change
			what you have to do.""");
	}

	/**
	 * 7. THE ONE WHO CAME BACK. A survivor's account, transcribed and untidied.
	 *
	 * Eleven weeks in cell nine, and the men doing it were the town's own. The
	 * point is stated by the man it was done to: the ordinary ones had to be cut
	 * too, or the numbers mean nothing. The man with the book was Steve, and he
	 * was only ever testing himself.
	 */
	public static ItemStack seven() {
		return book("7. the one who came back", "Addexio",
			"""
			7. THE ONE WHO CAME
			BACK.

			Taken down as spoken.
			Cell nine. Eleven weeks
			inside.

			I have not tidied his
			words. Where he
			stopped, I have left
			the gap.""",

			"""
			\"They put me in on a
			Tuesday. Joren wrote
			my name in the book.
			He said sorry. He did
			say sorry.\"

			\"The first week was
			only questions. What is
			your wife called. What
			did you eat. Say the
			alphabet backwards.
			Easy things. I got
			every one of them
			right.\"""",

			"""
			\"Then a man came who
			was not from the
			town.\"

			\"He had a book and he
			asked the same
			questions and he did
			not listen to the
			answers. He was
			watching my hands. He
			said the answers do
			not matter. Only the
			hands.\"""",

			"""
			\"They took the door
			off cell four and put
			a lamp in and left it
			burning nine days, and
			the man in there
			never slept, and on
			the ninth day he was
			still not wrong. So
			they wrote down that
			the lamp does not
			work.\"""",

			"""
			\"They tried cold. They
			tried keeping us
			awake. Then they tried
			cutting, to see if we
			healed the way a man
			heals.\"

			\"I healed the way a
			man heals. So they cut
			deeper, because the
			shallow ones only
			proved the shallow
			ones.\"""",

			"""
			\"There was a woman in
			six. I will not give her
			name. Her daughter is
			still alive.\"

			\"They opened her arm
			from the elbow down
			and held it open with
			pins and asked her to
			name her mother, and
			she did, all the way
			through, and she was
			right every time.\"""",

			"""
			\"She was still right
			when she died.\"

			\"Here is what you
			have to understand.
			She was not one of
			them. Nobody in this
			hole was one of them.\"""",

			"""
			\"We were the ordinary
			ones. That is the point
			of us. You cannot tell
			them apart, so you
			have to do it to the
			ordinary ones as well,
			or the numbers mean
			nothing.\"

			\"He wrote that in his
			book. He said it just
			like that. The numbers
			mean nothing.\"""",

			"""
			\"Eleven of us went in.
			I came out.\"

			WHO THE MAN WITH THE
			BOOK WAS.

			He was Steve.

			The same Steve who
			farmed my valley
			before me. The same
			Steve who went under
			the hill and did not
			touch the door.""",

			"""
			Herobrine's friend.

			He was not trying to
			save anybody. He was
			trying to find out
			whether he himself
			would have come up
			out of that hole the
			same way.

			He found out that he
			would.

			WHERE TO GO.""",

			"""
			We closed the prison.
			We hanged nobody. I
			think about that.

			Then in the eleventh
			year two boys found
			where he lives.

			The church is south
			of here. Everyone
			who was left went
			there first, and there
			is a book on the altar.""");
	}

	// ---- 5. THE CHURCH ------------------------------------------------

	/**
	 * 8. WHERE HE LIVES. Two boys and a dog find the second door. The church is where
	 * two hundred people decided whether to walk into it, and where Wendel wrote
	 * down the question nobody would let him ask out loud. Four of nine came back,
	 * and what they saw was a paved road and lit windows: he built a house.
	 */
	public static ItemStack eight() {
		return book("8. where he lives", "Addexio",
			"""
			8. WHERE HE LIVES.

			He does not live in a
			house.

			Two boys following a
			dog found it in the
			eleventh year. A
			frame of black stone
			standing in a hollow,
			with the same purple
			light standing up
			inside it like water.""",

			"""
			The same door as the
			one in the square at
			Ashfold. He had one
			out here the whole
			time.

			WHAT THIS CHURCH WAS
			FOR.

			Everything left of us
			came here first.""",

			"""
			Not to pray, although
			we did that too. To
			decide. Two hundred
			people in one room,
			deciding whether to
			walk into a door.

			The cleric here was
			called Wendel. He was
			old, he was not brave,
			and he was the only
			one of us who said
			the true thing out
			loud.""",

			"""
			He said: before you
			let that man near you,
			ask Steve what he did
			to Herobrine under
			the hill.

			We told him it was not
			the time.

			So he wrote it down
			instead, which is why
			you can still read it.""",

			"""
			He was dead inside the
			month. Steve was four
			days' ride away, knew
			which night it was, and
			did not come.

			WHAT IS THROUGH IT.

			I went through. Nine
			of us went and four
			came back. I am one of
			the four and I will not
			write down most of it.""",

			"""
			I will write down this
			much, because you will
			need it.

			It is not a cave.
			Somebody built it.

			There is a castle
			over there with lights
			in the windows, and a
			road going up to it,
			and the road is paved,
			and the paving is laid
			in a pattern.""",

			"""
			He did not find a hole
			and crawl into it. He
			went somewhere and
			built a house.

			WHERE TO GO.

			Follow the map west.
			There is a small
			village at the end of it
			with a hall in the
			middle and a flag on
			the hall.""",

			"""
			That is where it
			stopped. That is where
			I nearly stopped with
			it.""");
	}

	// ---- 6. THE LAST HOUSE --------------------------------------------

	/**
	 * 9. THE LAST HOUSE. The one fight Addexio is not ashamed of, and it lasts a
	 * sentence. He reaches Herobrine, swings, connects, and wakes against the far
	 * wall with a hand that never works again. Sixty-one dead in one room. They
	 * wall the door up and tell the valley it is over.
	 */
	public static ItemStack nine() {
		return book("9. the last house", "Addexio",
			"""
			9. THE LAST HOUSE.

			Sixty people lived in
			this village.

			We came here in the
			twelfth year with
			everything we had
			left, because we had
			finally worked out how
			to make him come to
			us.""",

			"""
			You make him come by
			taking his door.

			HOW IT WENT.""",

			"""
			We drove him out of
			Ashfold first. Two
			hundred of us with
			iron and fire, in the
			streets where we had
			buried our own
			families, and it worked,
			and I have never
			been so certain of
			anything in my life.""",

			"""
			Then out of the fields.
			Then along the valley
			road for two days,
			losing four and five
			and six of us a night,
			and every one of
			them was somebody I
			had eaten with.

			Then here. To the hall
			with the flag on it,
			because his last door
			was underneath it.""",

			"""
			WHAT HAPPENED IN THE
			HALL.

			He was waiting in the
			hall.""",

			"""
			He had let us drive
			him. Twelve days of us
			thinking we were
			pushing, and he had
			been walking
			backwards to the one
			place where all of us
			would be standing in
			one room.""",

			"""
			I got to him. That is
			the only thing in ten
			books I am not
			ashamed of. I got
			close enough to swing,
			and I swung, and I hit
			him, and it was like
			hitting a doorframe.""",

			"""
			Then I was against the
			far wall with a great
			deal of my own blood
			on the boards and my
			left hand would not
			work.

			It has never worked
			properly since.

			Sixty-one of us died
			in this village. In one
			room. In about the time
			it takes to boil a pot.""",

			"""
			WHAT WE DID INSTEAD.

			We could not kill him,
			so we did the only
			other thing we could
			think of.""",

			"""
			We went down the stair
			under the hall and we
			walled his door up.
			Stone, then more
			stone, then earth. We
			cut warnings into it in
			three different hands
			so that nobody would
			ever mistake it for a
			cellar.

			Then we came up and
			told the valley it was
			finished.""",

			"""
			That was a lie. All of
			us knew it was a lie. We
			told it because people
			needed to plant wheat.

			WHERE TO GO.

			Down.""",

			"""
			There is a stair under
			this hall. The stone in
			it has gone black and
			glassy, and there is
			heat coming up out of
			it, and none of that
			belongs on this side.

			Which means the wall
			did not hold.

			The last book is at the
			bottom, next to the
			door.""");
	}

	/**
	 * 10. HE HAS BEEN SEEN. Written last spring, at the bottom of the stair, next to
	 * the hole in his own wall.
	 *
	 * The list of what he got wrong is the mod's own advice in order, and the last
	 * page is why the numbering exists at all: he is still alive, he refuses to say
	 * where he is because you already know, and he has been walking behind you
	 * since the first house. He came down here alone to leave this book at the
	 * door and then went back up to the farm to wait. See Company.arrives.
	 */
	public static ItemStack ten() {
		return book("10. he has been seen", "Addexio",
			"""
			10. HE HAS BEEN SEEN.

			I am eighty-one years
			old and I am writing
			this at the bottom of a
			stair I helped wall up
			sixty years ago,
			beside a hole in that
			wall that I did not
			make.

			WHAT HAS HAPPENED.

			He has been seen.""",

			"""
			Twice this spring in
			the valley. Once at the
			old farm where these
			books start. A man
			walking his fence line
			at dusk saw somebody
			standing in the wheat,
			not breathing.""",

			"""
			It is beginning again in
			the same order it
			came in the first time.
			Small things first.
			Torches out in a line.
			A door open and still.
			Prints going one way.

			You have been
			reading these in that
			order because that is
			the order it happens
			in.""",

			"""
			WHAT I GOT WRONG.

			All of it. Let me be
			useful and be exact.

			I did not believe Pip.
			Believe the one who
			comes up the ladder
			shaking.

			We watched the
			horizon. He is not on
			the horizon.""",

			"""
			We built a prison and
			let a man with a book
			into it, and in eleven
			weeks we did worse to
			ourselves than he did
			to Ashfold in three
			days. We did it
			because we were
			frightened and it felt
			like doing something.

			I stayed behind the
			cart.""",

			"""
			And when we could not
			kill him we hid him, and
			told everyone it was
			over, and left it for a
			stranger to find sixty
			years later.

			That is you.

			WHAT YOU HAVE TO DO.

			Not what we did.""",

			"""
			Do not wall it up. Go
			through it.

			He built a house over
			there with lights in the
			windows. A thing that
			builds a house can be
			found in it. A thing
			that can be found can
			be finished.""",

			"""
			Take iron, and take
			more than you think
			you need. Do not go
			alone.

			And do not trust a
			face because it knows
			your name. Ask it
			something only a
			friend would know, and
			watch the hands.

			WHERE I AM.""",

			"""
			I am still alive. That
			surprises me more
			than anything else in
			these ten books.

			And I am not going to
			tell you where I am,
			because you already
			know.""",

			"""
			I came down here on
			my own to leave this
			book at the door, and
			then I walked back up
			and went to the farm,
			because the farm is
			where anybody who
			picks up this trail
			starts. I sat on the
			wall and I waited.""",

			"""
			If you have read
			these in the order
			they are numbered,
			then I saw you at the
			first house and I
			have been behind you
			ever since.""",

			"""
			I am not much use. I
			am eighty-one and my
			left hand has not
			worked since the hall.
			But I have kept the
			good armour all these
			years for exactly one
			day, and I can still get
			in front of you once.

			That is all I have. It is
			more than anyone did
			for me.""",

			"""
			WHAT IS LEFT.

			Do not wall it up. Go
			through.

			My name is Addexio. I
			failed at this for sixty
			years.

			Let us go and finish it.""");
	}

	private static final int TITLE_FITS = 32;

	private static String title(String wanted) {
		if (wanted.length() <= TITLE_FITS) {
			return wanted;
		}
		int cut = wanted.lastIndexOf(' ', TITLE_FITS);
		String short_ = wanted.substring(0, cut > 12 ? cut : TITLE_FITS).trim();
		com.bloomlet.herobrine.HerobrineMod.LOGGER.warn(
			"book title was {} characters and the wire allows {} — \"{}\" became \"{}\"",
			wanted.length(), TITLE_FITS, wanted, short_);
		return short_;
	}

	private static ItemStack book(String title, String author, String... pages) {
		List<Filterable<Component>> written = new ArrayList<>();
		for (String page : pages) {
			written.add(Filterable.passThrough(Component.literal(page)));
		}
		ItemStack stack = new ItemStack(Items.WRITTEN_BOOK);
		stack.set(DataComponents.WRITTEN_BOOK_CONTENT, new WrittenBookContent(
			Filterable.passThrough(title(title)), author, 0, written, true));
		return stack;
	}
}
