package com.bloomlet.herobrine.structure;

import java.util.ArrayList;
import java.util.List;

import net.minecraft.core.component.DataComponents;
import net.minecraft.network.chat.Component;
import net.minecraft.server.network.Filterable;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.Items;
import net.minecraft.world.item.component.WrittenBookContent;

/**
 * THE STORY. TEN BOOKS, NUMBERED, ONE VOICE, IN ORDER.
 *
 * GENERATED. Do not edit this file — write tools/books/prose.py and run
 * tools/books/gen_books.py. Pagination is the reason: a page is about 114 pixels
 * wide and fourteen rows tall and overflow is SILENT, so a hand-edited paragraph
 * loses its last line and nobody finds out for months. Seven pages of the first
 * set were clipped exactly that way.
 *
 * WHO IS TELLING IT. Addexio. He lived in the first house, he was at every one
 * of these places while it happened, and he is the companion you can still find
 * who walks in out of the distance at that same first house — see
 * Company.arrives. Book 10 is addressed to you and its last page is the man
 * already standing next to you, which is the whole reason the books are
 * numbered rather than scattered.
 *
 * HE IS A HERO WHO FAILED. He had a weapon every time. Book 4 is the one the
 * rest hangs off: he was thirty feet from a church with four children in it,
 * holding an iron sword, and he stayed behind a cart. He writes it in one
 * sentence and does not soften it. The arc after that goes downward — a tower
 * watching the wrong direction, a prison his own town built, a fight he lost,
 * and a wall he helped put up over a door instead of going through it.
 *
 * WHAT REPLACED WHAT. There were twenty-two books in ten hands: Alma's house
 * book, Toby's, Joren's protocol, Kadmus on the watch, and Steve's six documents
 * laid over the top. Every one was good and the whole was unreadable — a player
 * finds these one at a time, hours apart, between two other things, and
 * assembling a plot out of ten strangers' diaries is a thing nobody does.
 *
 * Steve is still in it. He is a character in Addexio's account now instead of
 * its narrator, and book 7 is where he arrives: the man with the book who came
 * to the prison and was only ever testing himself.
 *
 * WHAT EVERY BOOK HAS TO DO, or it is scenery:
 *
 *   MAKE THIS PLACE MATTER   what happened in the room you are standing in
 *   POINT AT THE NEXT ONE    by name, with a reason to walk there
 *   MOVE THE STORY ON        so that the order is not decoration
 *
 * Book 1 is in the farmhouse chest WITH THE MAP, because page one says "There is
 * a map in this chest" — the two cannot be separated any more without making the
 * text wrong. Book 6 carries the mimic tells that used to be theProtocol, in the
 * building that was dug to answer that exact question and answered it the worst
 * possible way.
 *
 * EASY WORDS AND SHORT LINES. Nineteen characters to a line means a long word
 * costs a line and a subordinate clause costs a page, and it is read on a screen
 * by somebody who is being hunted.
 */
public final class HouseBooks {
	private HouseBooks() {}

	// SIX BOOKS, ONE IN EVERY PLACE, FIVE PAGES EACH. Each one says, plainly, what
	// he did here and to whom, and where the next book is. Plain prose: the book
	// wraps its own lines. No hints, no "it was not a fox". He killed people, and
	// the pages say how.

	/** 1. the farm. */
	public static ItemStack one() {
		return book("1. the farm", "Addexio",
			"My name is Addexio. This was my farm. He came here first. There are six books, one in every place he has been. Read them in order and you will know what he is and how to kill him.",
			"The first night he stood in my corn and stared at the house until dawn. No lantern. Two white eyes. My daughter Lise waved at him from her window. She was seven. He waved back.",
			"The third night he came inside. My wife screamed once. He had her by the hair in the kitchen and he put her head through the table. Then he smiled at me and walked out through the wall.",
			"A week later he tore the door off the frame and carried Lise out over his shoulder while I lay with a broken leg screaming her name. She did not scream. She looked at me and smiled. Like him.",
			"On her window, in her blood: MINE. Then he burned the barn with the animals shut inside, so I would understand. The map to the town is at the top of the tower. Do not sleep in this house. He comes back to it.");
	}

	/** 2. the town. */
	public static ItemStack two() {
		return book("2. the town", "Addexio",
			"He reached the town two days before I did. By the time I came through the gate they had already hanged three men for things he had done.",
			"Tomas the baker drowned his own daughter in the horse trough on the square. Forty people watched. When she stopped moving he dried his hands and asked who wanted bread. His eyes had a black dot in them. That is his mark.",
			"They hanged Tomas at noon. At dusk he was back in the bakery with the rope still on, kneading dough with the skin coming off his hands. Nobody ate the bread. It smelled of meat.",
			"He took eleven children in one night, out of locked rooms. The parents dug into the hill under the church to hide the rest. Half the town went down there. None of them came back up.",
			"They are still down there. Call a name and they answer with yours. Do not answer back. He learns voices. The map onward is in the library under the church. Take it and leave.");
	}

	/** 3. under the hill. */
	public static ItemStack three() {
		return book("3. under the hill", "Addexio",
			"This is his house. Not a lair. A house. He built it under the tower and lived in it for years. There is a bed. He slept in it.",
			"The table is set for two. The second chair was for Lise. Her ribbon is still tied to it. She sat across from him every night for a year and watched him eat. He does not eat food.",
			"The back room is shelves, and every book on them is a list of names. Every farm for forty miles, every soul, in his hand. A red line through the ones he has finished with. I counted nine hundred lines.",
			"Lise is on the third shelf. There is no line through her. Under her name he has written: NOT YET. STILL USEFUL.",
			"He came home while I was reading. I hid in the pool, under the water, with my knife. He stood over it and looked straight down at me, and laughed, and left. He wants me writing. The map to the prison is in the chest by the stair.");
	}

	/** 4. cell nine. */
	public static ItemStack four() {
		return book("4. cell nine", "Addexio",
			"The prison was our idea. Lock up anyone he had touched before they turned. Iron doors, one warder with the keys. It kept them in. It also kept him in with them.",
			"By the second month the warder was in cell four, because his wife said his voice had changed. The man who locked him in was in cell six by Friday. Anyone could say it of anyone. Everyone did.",
			"Marta scratched STILL MYSELF into her wall every morning for eleven days. On the twelfth the words were carved into the ceiling, and Marta was hanging from the bars by her own hair.",
			"Cell nine. A boy went in on Tuesday because he would not blink. On Wednesday the ceiling was red from wall to wall and the floor was empty. No body. His teeth were pushed into the door frame in a neat row.",
			"Something lives in nine now. It does not move while you look at it. Do not stop looking. Walk backwards to the stair. The last four of us dug out through the back wall. The map is in the chest. Not the tunnel at night.");
	}

	/** 5. the church. */
	public static ItemStack five() {
		return book("5. the church", "Addexio",
			"He lived under the altar. Under it. Father Ambrose fed him for a year and called it prayer. Then he began bringing him people, and he called that prayer too.",
			"Eleven of us went down the altar stair to drag him into daylight and finish it. Four came back up. They wore our friends' faces and walked in their clothes, and the eyes were his.",
			"Ambrose lit a fire to burn the four. He walked into it himself instead, and stood in the flames staring at me without a sound until his face slid off. Ambrose had been dead a month.",
			"That night I killed one of the four with my hands. It had my brother's face and it said my name in his voice while I did it. I do not know if it was him. I have not slept since.",
			"Nineteen of us are left. We are going to the last house and through his door, to end it or die there. Our names are on the church door. If you are reading this, we failed. The map is in the chest.");
	}

	/** 6. the last house. */
	public static ItemStack six() {
		return book("6. the last house", "Addexio",
			"Nineteen of us came down these stairs to the door. Eleven came back up. I am writing this on the way down for the second time. There will be no seventh book.",
			"The door under the floor is a hole in the world, and it breathes. Hold your hand near it and your hand is cold for a day. Put your hand in it and you lose the hand. Erik did.",
			"Eight went through with ropes round their waists. For a minute they shouted that it was dark and raining. Then one voice spoke through all eight of them and said our names, one by one, and the ropes went slack.",
			"Only Jorunn came back. She stood in the frame, dripping, and said IT IS BEAUTIFUL. Her mouth had too many teeth. I killed her with an axe before she finished. It took three strokes. God forgive me.",
			"On his side is a city built of the people he took, and a castle, and he sits in it waiting. For YOU. The door opens one way. Go through and finish him, or stay. I am going now. Come and find me. Bring everything.");
	}

	private static final int TITLE_FITS = 32;

	private static String title(String wanted) {
		if (wanted.length() <= TITLE_FITS) {
			return wanted;
		}
		int cut = wanted.lastIndexOf(' ', TITLE_FITS);
		String short_ = wanted.substring(0, cut > 12 ? cut : TITLE_FITS).trim();
		com.bloomlet.herobrine.HerobrineMod.LOGGER.warn(
			"book title was {} characters and the wire allows {} — \"{}\" became \"{}\"",
			wanted.length(), TITLE_FITS, wanted, short_);
		return short_;
	}

	private static ItemStack book(String title, String author, String... pages) {
		List<Filterable<Component>> written = new ArrayList<>();
		for (String page : pages) {
			written.add(Filterable.passThrough(Component.literal(page)));
		}
		ItemStack stack = new ItemStack(Items.WRITTEN_BOOK);
		stack.set(DataComponents.WRITTEN_BOOK_CONTENT, new WrittenBookContent(
			Filterable.passThrough(title(title)), author, 0, written, true));
		return stack;
	}
}
