package com.bloomlet.herobrine.structure;

import java.util.ArrayList;
import java.util.List;

/**
 * LAY PROSE OUT ON A BOOK PAGE THE WAY THE GAME ACTUALLY DOES IT.
 *
 * Everything in this mod that writes a book has been guessing. HouseBooks does
 * not — it is generated by tools/books, which measures in pixels and rows and
 * asserts every page — but the notes dropped in chests, the accounts in the
 * town and the pages he leaves behind all packed their text by CHARACTER COUNT,
 * which is a different thing that happens to be close.
 *
 * A page is about 114 pixels wide and 14 rows tall, and the glyphs are not the
 * same width: an `i` is two pixels, an `l` is three, a space is four, most are
 * six. So a budget of 250 characters is thirteen rows of ordinary prose, fifteen
 * rows of anything with narrow letters in it, and it cannot see at all that
 * every blank line between paragraphs costs a row of its own.
 *
 * AND OVERFLOW IS SILENT. A fifteenth row is simply not drawn. No error, no
 * warning, and the sentence it was in stops mid-word — which is how a carefully
 * written note ends up reading as garbage. One of the twelve chest notes was
 * losing its last two rows this way, and nobody could have found that by looking
 * at the source.
 *
 * So the measurement lives here now, in one place, ported from bind.py so the
 * two agree. Anything that writes a book can ask for pages that fit instead of
 * hoping.
 */
public final class Pages {
	private Pages() {}

	public static final int WIDE = 114;
	public static final int ROWS = 14;

	/**
	 * The glyph widths, and they are measured rather than assumed.
	 *
	 * Taken off the vanilla font's own advance table. Everything not listed is
	 * six, which is true of every letter and digit except the handful below.
	 */
	private static int glyph(char c) {
		return switch (c) {
			case '!', '.', ',', ':', ';', '|', 'i' -> 2;
			case '\'', 'l', '`' -> 3;
			case ' ', 't', '[', ']', 'I' -> 4;
			case 'f', 'k', '(', ')', '{', '}', '"', '<', '>', '*' -> 5;
			default -> 6;
		};
	}

	public static int width(String s) {
		int px = 0;
		for (int i = 0; i < s.length(); i++) {
			px += glyph(s.charAt(i));
		}
		return px;
	}

	/** One paragraph, broken into the lines the game will draw. */
	public static List<String> wrap(String paragraph) {
		List<String> out = new ArrayList<>();
		StringBuilder line = new StringBuilder();
		for (String word : paragraph.trim().split("\\s+")) {
			if (word.isEmpty()) {
				continue;
			}
			String trial = line.length() == 0 ? word : line + " " + word;
			if (width(trial) <= WIDE) {
				line.setLength(0);
				line.append(trial);
			} else {
				if (line.length() > 0) {
					out.add(line.toString());
				}
				line.setLength(0);
				line.append(word);
			}
		}
		if (line.length() > 0) {
			out.add(line.toString());
		}
		return out;
	}

	/**
	 * TEXT HAND-WRAPPED IN THE SOURCE, REFLOWED AND THEN LAID OUT PROPERLY.
	 *
	 * Three sets in this mod were authored as Java text blocks with the line breaks
	 * put in by hand, on the reasonable assumption that what you see in the editor
	 * is what appears on the page. It is not. A hard newline IS a line break to the
	 * game, and then the game wraps whatever is left over — so a source line of 379
	 * pixels is not one row, it is four.
	 *
	 * Measured: Testimony was over the limit on all twelve of its pages, nineteen
	 * to thirty-one rows each. JournalPages on fifteen of sixteen. Between them and
	 * Remembering, TWO HUNDRED AND FORTY-FIVE ROWS of finished writing were never
	 * drawn at all — every one of those pages ended mid-sentence and the rest of it
	 * simply did not exist on screen.
	 *
	 * Which is why the books read as nonsense. Not the prose: the prose was there,
	 * behind a page that stopped at fourteen rows without saying so.
	 *
	 * So the source's own line breaks inside a paragraph are treated as what they
	 * are — soft wrapping somebody did to keep the file readable — and thrown away.
	 * A BLANK line still means a new paragraph, because that is a real break the
	 * author intended.
	 */
	public static List<String> reflow(String authored) {
		StringBuilder prose = new StringBuilder();
		for (String paragraph : authored.strip().split("\n\s*\n")) {
			if (paragraph.isBlank()) {
				continue;
			}
			if (prose.length() > 0) {
				prose.append("\n\n");
			}
			prose.append(paragraph.replaceAll("\\s*\n\\s*", " ").trim());
		}
		return bind(prose.toString());
	}

	/**
	 * Prose in — paragraphs separated by blank lines — pages out, all of which fit.
	 *
	 * A paragraph longer than a whole page is split across pages rather than
	 * dropped, because losing the end of a note is the failure this class exists
	 * to remove and refusing to write it at all is not an improvement.
	 */
	public static List<String> bind(String prose) {
		List<String> pages = new ArrayList<>();
		List<String> page = new ArrayList<>();
		for (String paragraph : prose.strip().split("\n\\s*\n")) {
			if (paragraph.isBlank()) {
				continue;
			}
			List<String> block = wrap(paragraph);
			// A blank row for the break, but only if something is above it.
			int need = block.size() + (page.isEmpty() ? 0 : 1);
			if (!page.isEmpty() && page.size() + need > ROWS) {
				pages.add(String.join("\n", page));
				page = new ArrayList<>();
			}
			if (!page.isEmpty()) {
				page.add("");
			}
			if (block.size() > ROWS) {
				for (int from = 0; from < block.size(); from += ROWS) {
					pages.add(String.join("\n",
						block.subList(from, Math.min(block.size(), from + ROWS))));
				}
				continue;
			}
			page.addAll(block);
		}
		if (!page.isEmpty()) {
			pages.add(String.join("\n", page));
		}
		return pages;
	}
}
